@baseApi=https://api.tastyworks.com
@optionChains={{baseApi}}/option-chains
@contentType=application/json
@userAgent=tastytrade-api-client/1.0
@authorization=not-real

### Get Symbol option chain
GET {{optionChains}}/WBA
Content-Type: {{contentType}}
User-Agent: {{userAgent}}
Authorization: {{authorization}}
