@baseApi=https://api.tastyworks.com
@publicWatchlists={{baseApi}}/public-watchlists
@contentType=application/json
@userAgent=tastytrade-api-client/1.0
@authorization=not-real

GET {{publicWatchlists}}
Content-Type: {{contentType}}
User-Agent: {{userAgent}}
Authorization: {{authorization}}

### Specific watchlist
GET {{publicWatchlists}}/tasty%20IVR
Content-Type: {{contentType}}
User-Agent: {{userAgent}}
Authorization: {{authorization}}
